### ISSUE TITLE
Guidance on Video URL format

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Marketplace.Issues#10]
Currently, the [Listing page](https://marketplace.umbraco.com/listing) says that the `VideoUrl` property is "A URL to a video file for embedding". Could this be expanded on? e.g. is it YouTube only, or must support oEmbed?

For my Contentment package, I have a series of introduction videos in a YouTube playlist, so I added this to my `umbraco-marketplace.json` file...

```
"VideoUrl": "https://www.youtube.com/watch?v=wADPwnJrTfg&list=PL8grlRt7-8oVULPYJpqido5QItRsJBt3M&index=1"
```

Alas, on the [Contentment package page](https://marketplace.umbraco.com/package/umbraco.community.contentment), this has a playback error.  I can try with just the initial video of the playlist, but then I'm mucking around with what values I think might work, as opposed to knowing what is actually supported.

**Comment by AndyButland** [comment]
@nathanwoulfe - we've discussed this one, so when you have finalised the work you are doing, please can you update this description on the `listing.ts` page to better reflect what we are supporting here?  Thanks.

**Comment by nathanwoulfe** [comment]
@AndyButland most certainly can.

For transparency, the plan is this:
 - support YouTube embed URLs eg `https://www.youtube.com/embed/qyYmS_iBcy4`
 - support Vimeo embed URLs eg `https://player.vimeo.com/video/771124484`
 - transform YouTube video URLs into YouTube embed URLs eg `https://www.youtube.com/watch?v=qyYmS_iBcy4` is parsed to `https://www.youtube.com/embed/qyYmS_iBcy4`

For any other URLs, be that a YT playlist, another streaming platform, a URL to an MP4 or similar, we'll show a card with a link off to that asset. We did consider oEmbed, and will reconsider if there's enough demand for other services, but for now YT and Vimeo should be sufficient.

I suppose though a logical request might be multiple videos URLs to cater to playlists.

Was also suggested that we consider an object (or an array of), to allow specifying only the video ID and the service name, and then relying on the Marketplace to construct the appropriate embed URL.

**Comment by nathanwoulfe** [comment]
Content on listing page will be updated in the next deployment.

**Comment by leekelleher** [comment]
Super, thanks @nathanwoulfe @AndyButland.

To clarify on my URL, e.g. `https://www.youtube.com/watch?v=wADPwnJrTfg&list=PL8grlRt7-8oVULPYJpqido5QItRsJBt3M&index=1` would that be parseable into the embed format?
