### ISSUE TITLE
Profile SVG Logos do not load

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Marketplace.Issues#11]
When setting an SVG as a profile image it doesn't load

![image](https://user-images.githubusercontent.com/9937803/203811364-a56e3bd2-8ae5-4dfd-9df7-450bb6bbcfb5.png)

**Comment by AndyButland** [comment]
Can we support this @nathanwoulfe?  If not, we should update on the "List my package" screen.

**Comment by AndyButland** [comment]
Actually, I think we'll just have to specify a PNG or JPG here.  It seems the issue may be more to do with serving them via image sharp, so may be more involved to resolve.  I'll update the details to indicate this.

Hopefully it's not too much trouble to use a PNG or JPG here @AaronSadlerUK.
