### ISSUE TITLE
Guidance for marketplace descriptions

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco.Marketplace.Issues#12]
Can we provide guidance for writing the marketplace descriptions?

This is possibly because people have had their packages picked up via the tag, and haven't had a chance to see how they'll be presented in the marketplace.

But some don't really say what they are in the gallery, particularly if you were new to Umbraco.

eg

Core serializer for uSync to read / write information to / from Umbraco CMS

is probably fine for a Nuget explanation but less so for the Marketplace - when you go to Nuget to install, you usually know why you are installing it whereas the Marketplace feels a bit more, showy offy, hey come see what's here...

And then others, the explanation are too looooong

The URL Tracker makes url management easy. Your visitors will no longer be lost on your website as the URL Tracker watches how your website changes. Page moved or renamed? No problem! The URL 

I know you can expand it and see all the text.

but just wondered if we identified a 'Short Marketing Summary' field for populating this gallery with a character limit guide and actually if this already exists in the JSON somewhere then would it be worth reaching out to the package owners, to offer marketing rewording suggestions to fit in with the feel and buzz of the market place?

**Comment by AndyButland** [comment]
Have added a little more detail explaining this on the "List my package" page, and also added the option for package owners to provide an alternative description via the `umbraco-marketplace.json` file.

This way that can have a description for NuGet, and a different one for the Umbraco Marketplace, if they want to present their package slightly differently between the two locations.

This will be live when we update the site on Monday.

**Comment by marcemarc** [comment]
Yes, Thanks @AndyButland and also allows us to create a PR to the package owner with suggestions of new wording for the marketplace only, and leaves the current Nuget package description intact, reflecting the different audiences!
