### ISSUE TITLE
Idea: Sync Contributors with Github Contributors

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#13]
Here is an idea. It would be ideal if I didn't need to sync and manually maintain a list of contributors and if could be automated by syncing the list of contributors for me.

The thought is to add a flag in the JSON that would then use the list of contributors available on the public GitHub readme.

```
"SyncWithGithubContribs": true,
```

**Comment by callumbwhyte** [comment]
I've been adding these manually, which is fine as I was maintaining a list of H5YR's in the README before anyway... But automating this would be ace 😄

**Comment by AndyButland** [comment]
We've prepared this feature now - you can trigger it if you provide a `SyncContributorsFromRepository` flag in the JSON file like I've done in [this one here](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/blob/main/umbraco-marketplace.json).

If this flag is set, AND you haven't provided a list of contributors explicitly, AND the [source code repository as defined in the NuGet package](https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/) is set and is a GitHub one, we'll pull in the contributor list from GitHub.

Will push to production tomorrow morning.

**Comment by warrenbuckley** [comment]
@AndyButland don't forget to ensure the docs/JSON schema note this change as well.
https://marketplace.umbraco.com/listing

Thanks for working on this 👍
