### ISSUE TITLE
Are there plans for identifying packages that work on Cloud?

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Marketplace.Issues#14]

**Comment by nathanwoulfe** [comment]
![image](https://user-images.githubusercontent.com/3248070/204396324-99f83bdf-3cae-423b-9c7e-bd51c1348052.png)

Yup, sure is. I'm not 100% sure on how we're identifying such packages, but we have the capacity to highlight these.

**Comment by AndyButland** [comment]
Yes, we have the database, API etc. in place so this feature could be used if we wanted to.  However it needs some further consideration about how and whether to present this information.

Obviously it's a moderation task that requires someone to be given time to do. And it perhaps presents the wrong impression -  both of packages and Cloud - given there's usually no reason why most packages don't work on Cloud, even if they haven't been manually validated.

**Comment by LottePitcher** [comment]
Appreciate the validation / moderation side of this that's tricky.  And also completely agree that it could give a negative impression about cloud support.

Recently I inadvertently released a package that didn't work on Cloud. It's a property editor that uses a 'treepicker` to select a data type, and this was using the node id in the uda file, not the udi. Anyway I've now added the code to fix that, so yes all good.

I guess if I feel strongly about being able to tell folks that I know that this works on cloud then I can just add a comment to that effect in the nuget readme.

**Comment by AndyButland** [comment]
I'll close this one, as technically we're actually in place for this (apart from displaying on the front-end). But I think due to the issues noted above this isn't really something we should be enabling now, without the moderation being in place.
