### ISSUE TITLE
Make PackagesByAuthor dynamic

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#15]
It's a bit of a pain having to maintain a list of `PackagesByAuthor` in the `umbraco-marketplace.json` file.

It would be awesome if these could be dynamically picked up based on the author.

**Comment by AndyButland** [comment]
Yes, am thinking this could be possible.  Using the `Authors` tag in the NuGet package is potentially open to abuse... e.g. I could call myself Callum and claim credit for packages I didn't build!

But using the package owner might be possible.  Unfortunately that's not exposed from the NuGet API, but we could get it from the NuGet gallery page content.  Then if we had that in our database, we could find all the other packages that also have that same owner.

Could be multiple owners?  But perhaps that's also OK... we'd show "other packages by any of the authors of this one".

**Comment by callumbwhyte** [comment]
In the case of multiple owners, perhaps take the first or have a way to specify the user from within `umbraco-marketplace.json` as a fallback? A `Username` field within `AuthorDetails` perhaps?

**Comment by AndyButland** [comment]
With the latest release we've add a means of automating this information. If it's provided in `umbraco-marketplace.json`, the packages indicated there will be used.

But if not provided, or it was provided and is removed, we'll instead automate this based on the package owner(s).  The "packages by this author" list will display all packages owned by at least one of the current package owners.
