### ISSUE TITLE
When viewing by category 'order by' filter doesn't appear to be working

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Marketplace.Issues#16]
You can replicate this by visiting https://marketplace.umbraco.com/category/editor-tools and then trying the A-Z or Z-A order by options.

The list reappears in a different order, but it's definitely not the correct one! The other order by options might not work properly either but they're harder to confirm as 'popularity stats' and 'date created' are not visible on the package details.

**Comment by AndyButland** [comment]
Thanks @LottePitcher.  I can see what's going on here.  We're ordering A-Z by package Id, which is previously what we had for the title of the package displayed.  However we're now using a title provided in the JSON file, or if that's not present, the title defined in the NuGet package... and only after that falling back to the package Id.

In short, we've updated the display of the title but not the field we're doing the ordering by.  Will get it fixed.

**Comment by LottePitcher** [comment]
Great @AndyButland - figured this one would be an easy fix :)

**Comment by AndyButland** [comment]
This will be fixed with the next release, likely early tomorrow morning.
