### ISSUE TITLE
A11Y - Keyboard navigation in the filter section only partially available

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Marketplace.Issues#17]
I can only tab into the version dropdown but Licence Type/Type/Order By are being skipped:

https://user-images.githubusercontent.com/304656/204523767-7c58d056-8cbe-46b1-8e0a-5916ece0c9dc.mp4

**Comment by nathanwoulfe** [comment]
That's a bit rubbish... Will fix today.

**Comment by nathanwoulfe** [comment]
Relates to https://github.com/umbraco/Umbraco.UI/issues/378, where the disabled state for the radio elements does not update when toggling the property value.

**Comment by nathanwoulfe** [comment]
Hey @nul800sebastiaan this is all good now (almost) - tabbing works correctly, but updating the radio values via keyboard doesn't resubmit the search. I'll close this one since the original issue is fixed, and will deal with the filters separately.
