### ISSUE TITLE
Filters are "sticky"

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco.Marketplace.Issues#19]
not sure if this is intended, but the package type filter seems to stick between pages. 

To Reproduce: 
1. Click on Intergrations link on marketplace homepage - you get a list of Intergrations 
2. Click on "Developer Tools" (or any of the categories) - the "Intergration" filter is still selected so you get no results. 

Its a little confusing, because you don't necessary expect the view to be filtered because you clicked on the link on the homepage?

**Comment by AndyButland** [comment]
Yes, I agree once you click back on the categories or the home page you'd expect your filters to be reset.  Particularly for this "integrations" link where you haven't actually opened up the filter panel and selected something.

There are though perhaps cases where you would want your filter to "stick".  E.g. if you set an order by, and then click between categories, you might want to retain the order to view.

But overall I think it's better to be consistent and reset.  The UI is very much indicating that you search "top down" - i.e. search or select category, and then apply filters.  So if you go back to the "top" it's probably cleanest and clearest to start over.

See what you think and perhaps you could we look at this next week please @nathanwoulfe?

**Comment by nathanwoulfe** [comment]
All sorted - wasn't clearing previous filters from state when reloading a card-deck. Agree it makes sense to clear all filters too.

Will be in the next production release.
