### ISSUE TITLE
Idea: Display more of Most Popular

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#2]
Currently I can only view the 12 most popular packages. It would be good to have a page of all packages that are sorted by popularity that are paginated (be it the number of downloads from nuget or the number of installs or any other current sorting)

**Comment by nathanwoulfe** [comment]
Kinda like https://marketplace.umbraco.com/all? 

Hadn't intended that view to be public/visible, but I don't see any harm in it. Just needs somewhere in the UI to make it accessible  (perhaps a third CTA card on the homepage, for browse all or similar)

**Comment by warrenbuckley** [comment]
If the page is made and its the same order as most popular Then in my mind for the UI/UX there could be one extra card in the same size as others that mentions to view all and a link to that page?

![image](https://user-images.githubusercontent.com/1389894/203730342-50c68209-1d6d-4e15-8839-4d3dde83ef04.png)

Thoughts @nathanwoulfe ?

**Comment by nathanwoulfe** [comment]
Oh yeah I like that - I've just now added a change to have 24 rather than 12 cards in the homepage decks, but makes better sense to have less with a link to all. Consider it done.

**Comment by nathanwoulfe** [comment]
![image](https://user-images.githubusercontent.com/3248070/204218077-5216a6dc-e067-468d-876f-65c0d65e3ea0.png)
