### ISSUE TITLE
Allow for Marketplace-specific Description data

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Marketplace.Issues#21]
Right now the marketplace is set up to pull the readme.md file from a NuGet package for display, but this has a few issues:

1. To update that file, a new NuGet release has to be published, which isn't great (especially if a package author is just adding some descriptive text or fixing layout issues)

2. The marketplace has different content needs than the Sourcceode repo (which is usually where the readme.md file is being designed to be displayed), and it would be nice to allow package developers to have a more "marketing-focused" description for the marketplace website (whereas the main readme might include developer-oriented documentation, etc.)

Perhaps the JSON file could have an inline MD property, or have a property for a direct url to a description .md file?

**Comment by AndyButland** [comment]
Hi @hfloyd - yes, this has been raised, I agree this would be a good idea, and is something we'll look at.  I'm not sure everyone would want to maintain two read me files, but I can see cases where people want to present different information here on Nuget and the Umbraco marketplace.

Just to make a couple of points in the meantime:

1. You can already have a Marketplace specific Description - this is the text that appears at the top of the listing.  For this we'll use what's provided in the NuGet package unless it's overridden in the JSON file.
2. You can actually amend the readme contents on NuGet without releasing an update to the package.  So for quick fixes like you describe, if you login on nuget.org you can make these amends via the "Manage package" link.

**Comment by AndyButland** [comment]
We've added the option now to provide a custom read me file for the marketplace.  Currently we take the read me from NuGet, but now if we find a file in the same location as the JSON file named `umbraco-marketplace-readme.md`, we'll import and display that instead. More detail and a permanent note of this feature is on the [listing page](https://marketplace.umbraco.com/listing) (starting from _"By default we will import and display the "read me" content..."_).

**Comment by hfloyd** [comment]
Cool! I bet @abjerner will be happy to hear this as well 😁

**Comment by abjerner** [comment]
@hfloyd yes, I noticed it in the schema, so I'm already using it 👍
