### ISSUE TITLE
Styling issues on listing page for XStatic

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#22]
https://marketplace.umbraco.com/package/xstatic

![image](https://user-images.githubusercontent.com/1389894/205589195-c16b91fb-a030-413d-b922-40f94dd4ad8d.png)

**Comment by AndyButland** [comment]
Looks OK to me?  Chrome/Windows.

**Comment by AndyButland** [comment]
Seems [my monitor isn't big enough](https://github.com/umbraco/Umbraco.Marketplace.Issues/issues/23)!

Will close this and reference it in this other issue.
