### ISSUE TITLE
Layout breaks on wide screens

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco.Marketplace.Issues#23]
When the screen is 2668px or wider the gallery images overlays the content instead of being below the content:

![image](https://user-images.githubusercontent.com/3674690/205625558-e2bc0481-c339-4745-93cb-f7d2a6e6016b.png)

![image](https://user-images.githubusercontent.com/3674690/205625730-30e61432-044b-4f43-ae13-33bdc2e57d54.png)

https://marketplace.umbraco.com/package/bergmania.openstreetmap
https://marketplace.umbraco.com/package/usync

**Comment by AndyButland** [comment]
See also the linked issue above, which shows the same reported issue.  @nathanwoulfe could you have a look at this one please?  I assume setting a max-width across the whole container will be best here.

**Comment by nathanwoulfe** [comment]
Building on main now - resolved by replacing flexbox layout with grid as it allows more declarative element positioning. Previous layout broke due to the HTML being built to allow displaying the sidebar last on small screens. Grid solves the same issue with less CSS.
