### ISSUE TITLE
Safari issue with (some) outlines

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Marketplace.Issues#25]
In Safari (v16.1 on Mac + iOS 16.1 on iOS) the outline on the "Close" button has rectangular corners:

<img width="856" alt="Screenshot of an open package dialog on the Marketplace where the Close button has a rectangular outline while the button itself has rounded corners" src="https://user-images.githubusercontent.com/5463/206021968-d32980bd-f856-403c-a044-9fada06bc10e.png">

The same is evident for the "Expand" buttons appearing on screenshots.

While it's likely a bug in Safari (the shape _should_ follow the border-radius, I think) it does look rather clunky :D

**Comment by nathanwoulfe** [comment]
Oh that's ugly. Will see what I can do, but I suspect your suspicion is correct and it's a quirky Safari behaviour. Might be related to using outline vs border too.

**Comment by nathanwoulfe** [comment]
@greystate looks like it's a known Safari issue => https://bugs.webkit.org/show_bug.cgi?id=20807

I'd prefer to leave it as-is, and let the browser (hopefully, eventually) correct it. It has only taken 14 years (yes, 14) for the fix to arrive, so surely it lands soon...
