### ISSUE TITLE
Packages should be sorted by relevance when searching for a specific text

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Marketplace.Issues#28]
The packages seem to be sorted based on downloads, which is probably fine in general. But when doing a text based search it might be useful if the packages are sorted in relation to that text. Eg. so that packages that contain the text in their names are prioritized over packages where the text is only part of the description or some other information.

Here are a few examples:

https://dev.marketplace.umbraco.com/search/table
https://dev.marketplace.umbraco.com/search/youtube

E.g. when searching for **youtube**, it seems that some packages are returned simply because they have a YouTube link in their description. I know this might be an edge case, but it means my **Limbo YouTube** packages is shown as the fifth result, while it should probably be the first if the packages are sorted by relevance.

**Comment by AndyButland** [comment]
Agreed, I've set up the API now such that there is a parameter that will order results that match on specific fields first.  The idea is that it is used when you provide a search text query, you also provide this parameter as the "order by" option (named `RelevanceToSearchText`).  It will then return results according to the following rules.

- Matches tag
- Matches package Id
- Has a match in the title
- Has a match in the description
- Has a match in the authors or owners.
- Has a match somewhere else.

I've set this up in branch `feature/sort-by-relevance` @nathanwoulfe.  Please could you pick up and amend the front-end to provide this parameter when the user triggers a text search?

It should also appears as an option in the "filter" panel, labelled "Relevance" - to allow the user to select a different order if they want to - but only when a text search has been triggered.  If the user has just clicked on a category, or via one of the options that views all of a type etc., it shouldn't be visible.

**Comment by nathanwoulfe** [comment]
Hey @abjerner this is live now - Limbo.YouTube is now the first result when searching 'youtube' 😃 

Per Andy's comment above, order by relevance is now an option when viewing search results only.

**Comment by abjerner** [comment]
Awesome 👍
