### ISSUE TITLE
Add Listing page help doc to some navigation

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#3]
I only discovered this page by reading the blog post that contained a link to it.
https://marketplace.umbraco.com/listing

Try to add it into the navigation or footer navigation perhaps?

**Comment by AndyButland** [comment]
It's in the footer navigation, labelled "List my package".  Obviously you missed it so perhaps it's not obvious enough, but pending further feedback I think this is probably the best place.  Might be a bit in the way putting it up in the header.

**Comment by warrenbuckley** [comment]
Yeh it didn't stand out to me next to the other links _(perhaps a different color to make it stand out against the others)_ @AndyButland
