### ISSUE TITLE
Can we have an RSS feed for packages?

### ISSUE THREAD

**Issue by LottePitcher** [umbraco/Umbraco.Marketplace.Issues#36]
I've had a look at the current marketplace website and can't see any sign of there being an RSS feed.

If there was then we could get this added to the list of RSS feeds that appear in the Umbraco Discord 'news' channel. Plus my own RSS reader of course...  

Our Umbraco had an RSS feed that I followed, I now realise why that went quiet a few months ago 🤦‍♀️

**Comment by nul800sebastiaan** [comment]
That's a big +1 from me as well please! We're currently surfacing new packages on Our Umbraco to Discord through the RSS feed. Also, would be good to have a feed on the old packages section to Our that points to what's going on in Marketplace. If there's a JSON API already then we could probably use that and transform it to Our and RSS.

**Comment by AndyButland** [comment]
Agreed, good idea.  Will look to add that.

**Comment by AndyButland** [comment]
I've added this now - currently just deployed to the dev site and so available at https://dev.marketplace.umbraco.com/rss.

I'll push live later this week but if either of you had chance to have a look and see if anything useful is missing or you spot any issues, thanks in advance.

**Comment by AndyButland** [comment]
Available on live now too.

**Comment by leekelleher** [comment]
Lovely! Already added to my feed reader. 😍

**Comment by LottePitcher** [comment]
Thanks Andy for sorting this so quickly 👏
