### ISSUE TITLE
Helping people new to Umbraco

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Marketplace.Issues#39]
As we know DXP is important to Umbraco and the wider community https://umbraco.com/blog/composable-dxp-for-umbraco/ but looking at the Marketplace with a beginners eye on Umbraco and Composable DXP its not clear what packages help with what.

Is it possible to have help text on the filters? And possibly a way to give guidance on what filters help with DXP (this is not me asking for help with DXP).  It would then be a method to get links between the main Umbraco site and the marketplace, as well as helping with keywords in SEO.

**Comment by AndyButland** [comment]
We've added some tooltips and a description below each category now @RachBreeze, which should make it a bit clearer what you'll find where and help with the issue you raised.  Thanks for the suggestion.

**Comment by RachBreeze** [comment]
OO I like it thank you
