### ISSUE TITLE
Listing Page: Docs for JSON object of AuthorDetails is lacking

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#4]
It would be good to show the nested properties full description of the `AuthorDetails` in the table describing each option and their usage,

![image](https://user-images.githubusercontent.com/1389894/203554069-3b9dd80c-a579-4a95-8237-9e9ad096ed93.png)

Perhaps it could be extra rows for each child key?

`AuthorDetails.Description` and `AuthorDetails.Url` etc...

**Comment by AndyButland** [comment]
Have broken it out as suggested to provide a bit more detail here.
