### ISSUE TITLE
Better Package Descriptions

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Marketplace.Issues#40]
Heya

I know that package descriptions aren't the remit of the marketplace but for a lot of packages there's no real description as to what the packages do on the summary page, or why I should pick one package over the other. It's missing the why from many descriptions.

**Comment by nathanwoulfe** [comment]
Hi @RachBreeze, I wholeheartedly 100% agree - a lot of the descriptions are average at best. Probably stems from the descriptions originally being written for use in a less-public context (ie NuGet search results), so most/many are not written from a marketing lens (ugh, I hate that I wrote that).

We have an outreach task in the backlog, I'll make a note to include an encouragement to improve copy.

N

**Comment by RachBreeze** [comment]
HI @nathanwoulfe 

Thank you, I did suspect that might be the case. And yes I'm not a fan of the phrase marketing either. I forgot to say the market place is a huge improvement on what we had before. So this and #39 are coming from a place of good intent :-) I really want it to succeed.

**Comment by nathanwoulfe** [comment]
All good @RachBreeze, absolutely appreciate the feedback!

**Comment by nathanwoulfe** [comment]
Given there's no work directly related to this issue, I'm going to close it. We'll make sure to include copywriting messaging in the package newsletter and any other outreach.
