### ISSUE TITLE
Sorting by `Recently updated` seems to be bugged

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Marketplace.Issues#43]
When doing a search in the Marketplace, it's possible to do a search ordered by **Recently updated**. Eg. like shown here:

![image](https://user-images.githubusercontent.com/3634580/218111915-25ec5e3a-9d61-4549-8190-2e04efdb2114.png)

Just by looking at the first four results, the fourth one should be before the others. And packages with more recent released should have been shown before these.

I'm noticing dates seem to be formatted in Danish. Could it be that dates are sorted as strings by `dd/MM/yyyy` (typical format in Danish) rather than ISO 8601 `yyyy-MM-dd`? 

![image](https://user-images.githubusercontent.com/3634580/218113010-1d1d1f78-be88-4528-9dc3-e2466330f3ca.png)

**Comment by nathanwoulfe** [comment]
Hey @abjerner I can't (fully) replicate this one - I was able to mess up the paging by changing the filters after loading a second page, which did result in one or two cards out of order, but they weren't in the first row so not sure it's related to this issue (regardless, I've fixed the paging for the next release).

Sorting all happens on the server, in the EF query, so we can rule out culture-specific date formatting. The dates are displayed using the local culture, hence your seeing Danish.

We do have a published and modified date, I need to check the difference between the two, might be that we should sort on the other value.

**Comment by AndyButland** [comment]
I've had a look at this.  We are currently using a last modified date, which does include changes other than the publishing of a new version of the package.  However I think it does make sense to consider only that (otherwise minor tweaks to a listing would count as an update and bring the package back to the top of the list.

This will be the case from the next release (which I plan to do tomorrow morning).

**Comment by abjerner** [comment]
Awesome. Works better already 👍 

Think @callumbwhyte will also appreciate this ☕ 😉
