### ISSUE TITLE
Deprecation of packages

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco.Marketplace.Issues#44]
Hi, 

It would be nice with an option to mark packages as deprecated and with the option to refer to another package instead.

Even better would if Umbraco marketplace could pull this information from NuGet.

![image](https://user-images.githubusercontent.com/2575817/221189069-73a33e99-04ef-4a07-9d3b-5269d0ed1a78.png)

**Comment by AndyButland** [comment]
Thanks @jesperweber for the suggestion here.  I hadn't realised we could get this from the NuGet API but looks useful information to pull in.

@nathanwoulfe - I've done the work on the back-end side for this, so this information should now be being pulled in and populated in the database.  It's available in the API via the following fields:

```
{
  ...
  "alternatePackageIdForRetiredPackage": "Enterspeed.Source.UmbracoCms",
  "alternatePackageIdForRetiredPackageExistsInCatalog": true,
  ...
  "isRetired": true,
  ...
  "retiredReason": "This package is no longer maintained. Please use our new package which works across multiple Umbraco versions and will update with new cool features.",
}
```

This is pushed up to the dev site so you should be able to use that for local testing.  `Enterspeed.Source.UmbracoCms.V10` is an example of a retired package, that is suggesting use of  `Enterspeed.Source.UmbracoCms`.

I'm thinking we need on the front-end:

- A fairly prominent box displayed on the package details page indicating that it's retired if `isRetired` is `true.
- Display the message provided in `retiredReason` (defaulting to some standard message this is empty or null),
- Lnk to the suggested alternative if that's provided in `alternatePackageIdForRetiredPackage`.  Either to the page on the Marketplace if it exists - based on `alternatePackageIdForRetiredPackageExistsInCatalog` - or the NuGet source page if not (probably in a new tab).

**Comment by jesperweber** [comment]
Wow you are working fast, awesome :-)

I think this would a a lot of value to the marketplace.

**Comment by AndyButland** [comment]
You should find with the latest release that deprecated packages are removed from the search results, and, if you did land on a deprecated package details page on a direct link, it'll show information about it being retired with a link to the replacement.
