### ISSUE TITLE
Query strings for filters

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#45]
The search filters don't add a query string into the request, making it hard to bookmark / share / return to a given search.

When we prepare UmbraCoffee each week we like to see what's new – this involves going to the marketplace, performing an empty search, opening the filters, and ordering by "Recently updated". It would be so much easier if I could just have that bookmarked!

**Comment by nathanwoulfe** [comment]
Ask and ye shall receive. There's an existing un-documented route available which should meet your requirements - /all returns a list of (surprise!) all packages, but can be further filtered by passing an additional route parameter:
 - /all/created
 - /all/updated
 - /all/downloads
 - /all/installs
 - /all/az
 - /all/za
This is available on dev.marketplace.umbraco.com, will be included in the next prod release which will no doubt be before the next UmbraCoffee instalment.
