### ISSUE TITLE
Support Ctrl / Cmd / Shift + Click to open links

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#46]
I frequently use Ctrl / Cmd / Shift + Click to open links in a new tab or window. This doesn't work when clicking a package card on the Marketplace, the card overlay just shows instead. It is possible to right click the card and "Open in new tab / window" though.

**Comment by nathanwoulfe** [comment]
Hey @callumbwhyte this is fixed now - will be available on dev.marketplace.umbraco.com shortly, and included in the next prod release.

**Comment by AndyButland** [comment]
Closing now as this has been deployed to production.

**Comment by callumbwhyte** [comment]
It seems this has stopped working... :-(

**Comment by nathanwoulfe** [comment]
It's you and your Mac 🥲 

Does SHIFT+CMD+CLICK work? In theory (ha!) it should, as we check for CTRL or SHIFT, but need to also check for the metaKey. I've pushed a change to dev, will be deployed soonish. If you could confirm that it's working (or not), that would be grand.

**Comment by callumbwhyte** [comment]
Works great on the dev site now @nathanwoulfe!

**Comment by AndyButland** [comment]
Thanks both - will push live on Monday (not today... Friday + Danish bank holiday not a good combination...).

**Comment by AndyButland** [comment]
Deployed to production now.
