### ISSUE TITLE
Icon for Umbraco supported / maintained packages

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#47]
It's great that an icon shows for HQ products or partner products, but it would be even greater if the Umbraco Integrations projects were also highlighted. This should probably have it's own icon to differentiate between the commercial offerings.

Example: we see a package called "Microsoft Dynamics CRM", it has a 1 line description, no docs, etc... (this is the case for most HQ integrations, clearly a separate issue) Without clicking into it and really looking it's hard to tell if it's trustworthy.

**Comment by AndyButland** [comment]
Thanks @callumbwhyte - we have a task in hand to write and update the descriptive text for these integrations on the Marketplace, as you're right that they are a bit sparse at present.

It was considered during the introduction of the HQ products icon to not add it to the integrations, so there's some distinguishing between fully supported commercial products, and the integrations (which we are supporting, and do keep on top of issues raised... but it's not quite the same as having the full weight of the Umbraco support team behind).

I'll assign this one to you @BoletteKern if that's OK, so you can update when we have the integration descriptions improved and in case there's more to add about flagging the integrations.  Perhaps as Calum suggests we look at a specific icon for these, to they are marked as being "from HQ" but not "fully supported commercial products from HQ".

**Comment by nathanwoulfe** [comment]
Heya @callumbwhyte this is live now - different colored U for HQ supported packages vs HQ developed integrations 👍
