### ISSUE TITLE
Cross-linking between packages in readme doesn't work

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.Marketplace.Issues#48]
Our **Limbo Structured Data** package was renamed for Umbraco 10 so that it is now called **Limbo Tables**.

In the readme of **Limbo Structured Data** I'm linking to **Limbo Tables**, but when clicking the link, the overlay closes, but I'm not sent to the **Limbo Tables** package like expected.

https://marketplace.umbraco.com/package/limbo.umbraco.structureddata

![image](https://user-images.githubusercontent.com/3634580/231986648-ab6c1622-e73a-4ab8-9479-ed518f4364bb.png)

I suppose this is because it's an internal link, and some routing kicks in. But would be awesome if this was possible.

**Comment by nathanwoulfe** [comment]
Hey @abjerner that should work, but I think you're right about routing taking over and not behaving as expected. Interesting though that opening to a new tab works, which makes me think it's related specifically to the routing logic in the package overlay...

Will have a look into it.

**Comment by nathanwoulfe** [comment]
Fix for this is on dev.marketplace.umbraco.com - now possible to link between packages from the readme 👍

**Comment by abjerner** [comment]
@nathanwoulfe awesome 👍

**Comment by AndyButland** [comment]
Closing now as this has been deployed to production.
