### ISSUE TITLE
Footer links don't work, or make sense in the backoffice.

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco.Marketplace.Issues#49]
In the Umbraco backoffice, the Marketplace experience is a little off.

The "Privacy", "Terms and Conditions" and "Report an issue" links don't work.

https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/7151793/a690579c-630a-4e05-bd32-715dc19c6d76

Also, the cookie settings don't work - it doesn't seem possible to change consent from within the backoffice (there are a lot of cookie-related console errors). That said, I don't think that third-party cookies should need to be a consideration at all in the Umbraco backoffice.

**Comment by AndyButland** [comment]
Seems we haven't scrolled down that far!  @nathanwoulfe - do you think we could simply hide these things?  We have the querystring coming from the back-office IFRAME so load `backoffice.css` only if in the back-office, so presumably we could hide the footer links and also find a way to not prompt for the cookie confirmation?

**Comment by nathanwoulfe** [comment]
Yup, I agree hiding the footer links makes sense. Backoffice view should be packages and very little else, it's not intended to be a full embed of the Marketplace. I need to confirm, but have a feeling we don't track at all in the backoffice, so cookies would indeed be redundant.

Leave it with me 😄

**Comment by nathanwoulfe** [comment]
@JasonElkin we aim to please - this is fixed now. No more footer in the backoffice, and a slightly improved header too.

**Comment by JasonElkin** [comment]
Thanks muchly @nathanwoulfe and @AndyButland!
