### ISSUE TITLE
Bug: Unable to see previous pagination arrow for screenshots

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#5]
https://marketplace.umbraco.com/package/umbraco.deploy.onprem

Open/expand a screenshot.
The pagination arrows underneath pointing left for previous is not visible until you mouse over the area that does

**Comment by nathanwoulfe** [comment]
Ah, the joys of dynamic colors - the arrow color is set to dark or light based on the dominant color from the icon, (eg light text on a dark color and vice-versa). 

I've updated to use the white background on the previous button, provided it is not disabled. If it's disabled, it has no background (this is the case for both buttons).

Will deploy later today.

**Comment by warrenbuckley** [comment]
Nice one. When it's deployed @nathanwoulfe feel free to close the issue
