### ISSUE TITLE
Navigating carousels using keyboard moves arrows

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#51]
When navigating the carousels via keyboard, the carousel arrows move position and the gradient overlay as well.

https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/832f905c-70a4-400e-909a-b277934421f2

**Comment by nathanwoulfe** [comment]
Oh that's pretty ugly, we can do a lot better 😄

**Comment by nathanwoulfe** [comment]
Annnnd should be much better now - can tab (or shift+tab) through the cards, with the deck scrolling accordingly. It's still possible to break it (I spammed the tab and shift+tab events), but in normal usage seems to be working nicely.

**Comment by bjarnef** [comment]
@nathanwoulfe cool, much better. It works as expected at "Most popular" and "Recently added" carousels.

Now we also have the same issue here at "Technical partners" :D 

https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/bc733097-1e08-4e5e-9ed8-95fbe7bcd227
