### ISSUE TITLE
Clicking external links opened in same window breaks when clicked within backoffice

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#55]
On marketplace in backoffice it breaks clicking external links if opened in same window/frame, e.g. GitHub links for Co-authors

https://marketplace.umbraco.com/package/dawoe.oembedpickerpropertyeditor

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/c104c40d-e576-4eed-81dc-33470383f0d4)

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/c8ac10ba-8e3f-4425-ad3d-d864e270ef5f)

The simplest fix is probably to add `target="_blank"` to these links similar to links at "Links" section.

**Comment by nathanwoulfe** [comment]
Hey @bjarnef, what browser are you using? All external links are using `target=_blank`, and I'm not able to reproduce your issue in Chrome.

**Comment by bjarnef** [comment]
Hi @nathanwoulfe 

I am using Chrome Version 115.0.5790.171
But when checking now I can't reproduce it. Make something was cached in the iframe or if changes was made regarding this at some point.

Will close this for now :)

**Comment by AndyButland** [comment]
We fixed it actually @bjarnef - after Nathan's comment we found the link you found that didn't have this attribute set.  Deployed to production this morning so you saw the results.

**Comment by bjarnef** [comment]
@AndyButland okay, makes sense then! 😄🎉
