### ISSUE TITLE
Clearer call to actions on the homepage

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/Umbraco.Marketplace.Issues#57]
Hi there

I think it would be helpful if there was a clearer call to action to see all of the "most popular" and "recently added" packages. At the moment, the call to action to see all of them is at the end of the carousel a user needs to click 9/10 times to reach it on desktop.

_I think there used to be a call to action next to the headings above the carousel._ 

Anyway, I reckon this would be helpful to users, to place an additional call to action above or below the carousels. Otherwise, that call to action is probably missed by the vast majority of users.

<img width="1600" alt="Screenshot 2023-08-16 at 11 07 53" src="https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/24275922/404c4af3-1815-4aa5-8656-506788e21c93">

Thanks!

**Comment by BoletteKern** [comment]
Hi Paul 
Thank you very much for bringing this up. It's correct, there has been a "Show all" button under "Most popular" and "Recently added". Currently, we are tracking the use of the buttons in the new design of Umbraco Marketplace, to determine how users are navigating the site. We will evaluate these data soon and most likely reintroduce the "show all" button, as you are not the first one to mention this. 
Best regards
Bolette

**Comment by ronaldbarendse** [comment]
We now have the [Explore all popular packages](https://marketplace.umbraco.com/all/popular) and [Explore all updated packages](https://marketplace.umbraco.com/all/updated) links below the package sliders again 💪🏻

**Comment by dalyUSN** [comment]
Great work everyone, cheers!
