### ISSUE TITLE
CORS Issue on validation page

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Marketplace.Issues#58]
Hi,

It looks like there is a CORS issue on the validators page:

https://marketplace.umbraco.com/validate

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/9937803/59b78bf4-0eee-47bd-908b-686a7f57cc71)

**Comment by nathanwoulfe** [comment]
Hey @AaronSadlerUK, thanks for letting us know - I've found the cause and have a fix on dev, just needs to be pushed though to live. Given that will likely happen before you read this, I'll close the issue now too. Thanks again.
