### ISSUE TITLE
Idea: Use keyboard left and right arrows to look through screenshots

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#6]
Add some keyboard functionality and use the left and right arrow keys to look through open screenshots.

**Comment by nathanwoulfe** [comment]
Heya @warrenbuckley, I've resolved this, with a few additional bonus bits for A11Y improvements.

Had to work around an issue where the slides can be positioned outside the viewport, but are brought into the viewport when focused (by keyboard nav or programmatically) - not brought into view elegantly but rather the viewport shifts to include the focussed element. To resolve that, I've removed the slides from the tab order, but ensured focus instead passes to the carousel controls so can still cycle through the slides. Also added a visible expand button for similar reason - if the slides aren't tabbed, the existing expand button is not accessible, so needed an alternate mechanism for opening the full-screen view.

Looks like this:
![image](https://user-images.githubusercontent.com/3248070/204714840-75ed20b8-0731-4f18-964e-7cae1d074fff.png)

With these changes, we can:
- L/R to scroll carousel
- Open fullscreen via the slide buttons or the new button (and bonus: if focusing the L/R buttons, keypress f will open fullscreen too)
- Exit fullscreen via ESC

Only bit that annoys me, is on smaller screens when the carousel sits above the white card (with the developer details), the tab order still puts the carousel last, as that reflects the HTML order. Not really a big deal, I'll live with it.
