### ISSUE TITLE
Apply type search to search input

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#61]
<p><span style="">The search input should also use </span><code style="">type=&quot;search&quot;</code><span style=""> instead of </span><code style="">type=&quot;text&quot;</code><span style=""> (the browser clear icon can eventually be hidden using CSS).</span><br> </p><p>It also implements potential action in https://schema.org/SearchAction : </p><pre><code>&lt;script type=&quot;application/ld+json&quot;&gt;
    {
        &quot;@context&quot;: &quot;https://schema.org/&quot;,
        &quot;@type&quot;: &quot;WebSite&quot;,
        &quot;name&quot;: &quot;Umbraco Marketplace&quot;,
        &quot;url&quot;: &quot;https://marketplace.umbraco.com/&quot;,
        &quot;potentialAction&quot;:
        {
            &quot;@type&quot;: &quot;SearchAction&quot;,
            &quot;target&quot;: &quot;https://marketplace.umbraco.com/search/{search_term_string}&quot;,
            &quot;query-input&quot;: &quot;required name=search_term_string&quot;
        }
    }
&lt;/script&gt;
</code></pre><p>but the <code>name</code> attribute of the search input doesn't match <code>search_term_string</code>:
https://stackoverflow.com/a/29341196 </p><p><img src="https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/4ff617d4-382d-4608-a95c-c93d0bb9e81c" alt=image> </p>

**Comment by AndyButland** [comment]
I'm not sure we can do too much about the misspelt packages really.  We are using Azure Cognitive Search under the hood, which kind of means we have to take what it returns for results of a query.  We do have a minimal set of synonyms mapped - but that's a list we maintain and it's not really feasible to add all different misspellings of packages.

@nathanwoulfe - could you have a look at the second part please to see if there's some presentation updates we should make please?

**Comment by AndyButland** [comment]
`type="search"` has been added to the search input box now.  Thanks for the suggestion @bjarnef.

**Comment by bjarnef** [comment]
Mainly to show a optimzed virtual keypad on mobile and tablet devices, but also a bit more semantic correct nowadays.

![Screenshot_20231003_083250_Chrome](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/9a2373a6-a570-4137-8bf0-a8e172ff190e)
