### ISSUE TITLE
Community maintainer option in search

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#63]
It would be awesome if the "Maintained by" dropdown could include an option for "Community" in addition to "Umbraco HQ" and "Technical Partner".

There is no way to filter *just* community packages right now.

---
_This item has been added to our backlog AB#33074_

**Comment by AndyButland** [comment]
Sounds a good idea - we can do that just with `community = !HQ && !Partner` I guess.  We'll take a look.

**Comment by AndyButland** [comment]
This has been added now.  Thanks for the suggestion @callumbwhyte.
