### ISSUE TITLE
Blue circle when mobile menu is open

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#65]
When mobile menu is open, it shows a blue circle.
It should probably turn the burger icon into a white SVG or a white close icon.

Maybe also less margin/padding to menu items, so most menu items fits on a single line e.g. "Analytics & Insights", "Campaign & Marketing" and "Themes & Starter Kits".

![Screenshot_20231003_083309_Chrome](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/36651c1b-95a1-4d29-b2da-7d7d73b7351c)

Furthermore consider to add `flex-shrink: 0` to icon wrapper to avoid text squeezing the icon.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/1ecf4f98-49e1-4dfc-838d-6fa74bbc9e1a)

---
_This item has been added to our backlog AB#33472_

**Comment by AndyButland** [comment]
Thanks @bjarnef - this is resolved now with the latest updates.
