### ISSUE TITLE
Tooltop is off from badge

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#66]
I noticed [uMarketingSuite](https://marketplace.umbraco.com/package/umarketingsuite) has a badge icon, but the tooltip is a bit off from the pointed location.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/ab882b34-3b87-46da-a16b-b7b7562f9b53)

Seems to be caused by `:host([x="right"]) small` styling override the CSS.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/3bede8c6-1700-4f6b-9fa1-7c40220220b2)

---
_This item has been added to our backlog AB#33663_

**Comment by AndyButland** [comment]
Thanks @bjarnef - this is resolved now with the latest updates.
