### ISSUE TITLE
Package not being listed

### ISSUE THREAD

**Issue by huwred** [umbraco/Umbraco.Marketplace.Issues#67]
Hi, I posted a new nuget package on friday, however it is not getting listed. Any idea why?

Our.Community.RssView 1.0.0

**Comment by AndyButland** [comment]
Hi @huwred - [it seems to be there](https://marketplace.umbraco.com/package/our.community.rssview) - and from the dates looks like it was loaded on Friday.

I did find an issue with the search engine indexing though which I resolved just now, so it could be that was causing it to not show up.  Hopefully all should be good now.
