### ISSUE TITLE
Wish: WebP and MP4 support

### ISSUE THREAD

**Issue by jpkeisala** [umbraco/Umbraco.Marketplace.Issues#68]
It seems that it is not possible to use WebP or MP4 (maybe even apng for animations?) on screenshots?  Could we have a possibility to make small animations on screenshots with something more higher quality that animated gifs?

---
_This item has been added to our backlog AB#35661_

**Comment by AndyButland** [comment]
You should find WebP images are rendered correctly now (and maybe others... we resolved this by upgrading the imaging component used, so possibly that's added support for further formats).  Videos though are really intended as a single one, provided via the `VideoUrl` field in the package owner JSON schema.
