### ISSUE TITLE
Listing page: Specify times jobs run

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#7]
After tagging a Nuget package with `umbraco-marketplace` how long does it take to appear?
if I add or update my JSON file, again how long does it take to appear.

I would be good to have a section on this page to list this, as it will a question that will come up time and time again.

**Comment by AndyButland** [comment]
Good idea, have added to the "List my package" screen:

![image](https://user-images.githubusercontent.com/1993459/204097186-f9760809-314b-48ef-a608-6881126a4a88.png)
