### ISSUE TITLE
Problem validating new package version

### ISSUE THREAD

**Issue by huwred** [umbraco/Umbraco.Marketplace.Issues#71]
I am trying to validate a new version of a recent package, however I am getting the error below

ERROR: Could not find package with ID Our.Community.CustomForm and version 1.0.2.

The package is listed on nuget

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/4870243/41e13899-7c7b-456c-bdda-23974852d715)

Any help appreciated

**Comment by AndyButland** [comment]
I just tried it and it seems OK for me.   Could just be NuGet caching, as I see it was only released 20 minutes or so before you posted this issue.  Might be the NuGet API lags a little behind what you see on the website, or maybe it just took a while before all caches were updated.

**Comment by huwred** [comment]
Ok, thanks for trying. Nuget must be having a slow day as it has worked previously within mintes of nuget publishing it.
