### ISSUE TITLE
Umbraco Marketplace filter is not working properly

### ISSUE THREAD

**Issue by gccornejo441** [umbraco/Umbraco.Marketplace.Issues#72]
I filtered by version 13 and selected the non-v13 option, but was redirected to a "Page not found" page.
<img width="1428" alt="marketplaceumerror" src="https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/64950833/04fedde2-2b43-459a-aaf8-588f45be54cf">
<img width="973" alt="notfound" src="https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/64950833/efc7c3e3-16f5-4287-aa44-c5d298da1d8f">

---
_This item has been added to our backlog AB#36433_

**Comment by nathanwoulfe** [comment]
Hey @gccornejo441 we have a fix for this, will be released once finished our internal review. Thanks for letting us know!

**Comment by AndyButland** [comment]
We've released the update now - filter looks to be working as expected.  Thanks both.
