### ISSUE TITLE
Package URLs which contain "sitemap" fail to load

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco.Marketplace.Issues#74]
It would appear that package URLs that contain the word "sitemap" fail to load when visited directly.
![Umbraco Marketplace Sitemap oddity](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/17008780/df4cd88e-328b-4716-b649-76233dfb4922)

Examples:
- [https://marketplace.umbraco.com/package/our.umbraco.blend.sitemap](https://marketplace.umbraco.com/package/our.umbraco.blend.sitemap)
- [https://marketplace.umbraco.com/package/aym.seotoolkit.umbraco.sitemap](https://marketplace.umbraco.com/package/aym.seotoolkit.umbraco.sitemap)

**Comment by AndyButland** [comment]
Thanks for reporting @OwainJ.  Looks like the particular issue here is that these packages end with `.sitemap`, and IIS interprets this as a file, and which is on it's list of default ones to block:
https://stackoverflow.com/questions/71594021/asp-net-web-app-returns-404-for-urls-ending-with-sitemap

Seems we can fix it by adding this to our `web.config` file:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <fileExtensions>
          <remove fileExtension=".sitemap"/>
          <add fileExtension=".sitemap" allowed="true" />
        </fileExtensions>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```

I've pushed this update and the two examples you shared load correctly now.
