### ISSUE TITLE
Description can break layout

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Marketplace.Issues#76]
It seems description of package potentially can break layout of a package on https://marketplace.umbraco.com/

E.g. this package by @warrenbuckley
https://marketplace.umbraco.com/package/umbraco.community.iconpack.iconoir

The text/description doesn't wrap within the content box and for some reason the package information is inside content box and not in right sidebar as other packages.

The missing version is probably just because v14 isn't handle yet although RC versions are on NuGet.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/06bdf88f-b243-4800-b447-918bdda1f54d)

Compared to uSync: https://marketplace.umbraco.com/package/usync

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/2f6df3fa-7df9-4c98-8c61-cc92beb2d98b)

**Comment by bjarnef** [comment]
Furhermore the description doesn't always look great because the readme description on GitHub repository is used as description.
Perhaps it could try parsing some basic HTML as `<strong>`, `<bold>`, `<em>`, `<italic>`, `<img>`? If not strip some HTML elements like `<img>`, but simple formatting may be okay like `<br>`, `<strong>` etc.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/887d63d6-424d-4b08-8e92-e3c5eaf15ac4)

**Comment by AndyButland** [comment]
Thanks @bjarnef - I think we need to here just strip out the encoded HTML image tags.  That's what' NuGet are doing if you look at the package there.  Probably for security reasons so makes sense we follow that.  Without that long encoded tag, the layout issues should be resolved.

> for some reason the package information is inside content box and not in right sidebar as other packages.

This is deliberate.  We've got some layout shifting going on depending on the length of the readme, so the pages are a little more balanced.

**Comment by bjarnef** [comment]
@AndyButland yes, it is most likely because of security concerns the HTML isn't rendered. On NuGet it seems the HTML is included as raw text under readme tab.

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/2919859/46b0996c-aa59-48ac-90b1-ba317b6b6ac0)

> This is deliberate. We've got some layout shifting going on depending on the length of the readme, so the pages are a little more balanced.

Not sure about this. I was actually looking at the information in right sidebar initially and wondered for a minute, why I couldn't find the repository, but then noticed it on left.
I see what you mean, but I think it makes in inconsistent. I think it would be confusing if e.g. NuGet did that for packages :)

It doesn't really bother me that right sidebar may be longer in some cases with minimal description. I am more for consistency.

**Comment by AndyButland** [comment]
The encoded HTML has been removed now:
https://marketplace.umbraco.com/package/umbraco.community.iconpack.iconoir

Will close this but just ping @nathanwoulfe for the comments on the layout changes.  Consistency is valuable certainly if you are quite familiar with the Marketplace and searching through several packages.  On the other hand, first impression of landing on a package page is also important, so we have to trade these off.  I suspect we'll leave as is for now but see what other comments we get on this and consider as we evolve the site.
