### ISSUE TITLE
uSync Active installs ?

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco.Marketplace.Issues#79]
Not sure if i have somehow managed to deplatform myself 😄 , as we have pushed out an update today (no different than we normally do) 

but uSync is apparently has fewer active installs that uSync.Complete and uSync.Forms. both of which require it?

https://marketplace.umbraco.com/category/developer-tools

**Comment by abjerner** [comment]
Maybe it's just an integer overflow? 😁

**Comment by AndyButland** [comment]
Looks to be sorted now @KevinJump.  Sorry about that.  I don't think it was anything to do with your release, but for some reason in the latest batch of telemetry data there were some records that revealed a bug in how we were aggregating the data across case sensitive names.  In short, a very low value for "usync" was overwriting the bulk of the data coming from "uSync".

Anyway, I've pushed the fix and re-run and see uSync correctly "re-platformed" now.
