### ISSUE TITLE
"Explore all recent packages" link not working

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco.Marketplace.Issues#80]
On the marketplace homepage, select "Explore all recent packages"

This should preselect the Order by filter with "Recently added".

Filter is incorrectly marked with "Most active installs"

![recent](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/22817718/3ff2bb49-160d-46e8-ad7b-8c152d7004ba)
![filter](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/22817718/fbe87942-fa9d-4e5d-8fdb-be6b5f41d9cc)

---
_This item has been added to our backlog AB#41989_

**Comment by AndyButland** [comment]
This has been fixed now.  Thanks for reporting @marcloveUSN.
