### ISSUE TITLE
Packages don't show in Google

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Marketplace.Issues#81]
Since the move to the Umbraco Marketplace it's become increasingly difficult to find packages via Google. This was the way I typically found packages from Our in the past.

One example, my own package Meganav, searching for "umbraco meganav" the marketplace does not appear at all. Our, GitHub, NuGet all show up in the first couple of results.

Other notable examples with the same behaviour: "umbraco usync", "umbraco slimsy".

Is there something special about these packages that means they don't rank? Or a bug? They are all included in the sitemap.xml so unclear why they haven't been indexed...

**Comment by leekelleher** [comment]
Always the outlier, "umbraco contentment" shows up with a Marketplace link for the second result. 😆 

Screengrab on Incognito mode (_so not a personalised search, I don't think, you can never be sure with cookies, anyways_) ...
![Screenshot 2024-07-03 111811](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/209066/e16ee639-3a49-4f83-91d3-8a19994d8960)

But yes, I experience the same for uSync, Slimsy, et al. 🤔

**Comment by nathanwoulfe** [comment]
Looking at Google's search console, there are issues with duplicate canonical URLs (caused by differences in casing) preventing pages from indexing. I'm going to remove the canonical link from non-duplicate pages and request reindexing, and we'll see what happens...

Not a quick fix, but hopefully the correct one.

**Comment by nathanwoulfe** [comment]
On second thoughts - we should be keeping the self-referential canonical. Instead, I'm adding a rewrite rule to redirect to lower-case URLs, which should do the trick.

**Comment by nathanwoulfe** [comment]
Hey @callumbwhyte @leekelleher, I think I'm still chasing this one - I've added a 301 to redirect to lowercase URLs, which match our sitemap and the canonical tags on the package pages, but Google still isn't happy (selects the upper/mixed case URLs. I've re-requested indexing, but if either of you have suggestions in the interim, I'm all for it.
