### ISSUE TITLE
All categories are redirected to /error/404

### ISSUE THREAD

**Issue by ghost** [umbraco/Umbraco.Marketplace.Issues#83]
Whatever category I try to open or whatever query I try to search for  I get redirected to error 404 page.
Tested in Chrome and Vivaldi. 
Opening a package from the home page from the list of 'Recently added' or 'Most popular' works normally.
![marketplace](https://github.com/user-attachments/assets/5c056d14-e512-4aeb-aae0-4bb988be7342)

**Comment by AndyButland** [comment]
We are not seeing this on our side @gregor-tusar-sowa (tried from a couple of locations).  Is it still an issue for you please?

**Comment by ghost** [comment]
Works now:

![image](https://github.com/user-attachments/assets/e37aab32-c0fc-4601-a801-e614f4cf0d16)

**Comment by nathanwoulfe** [comment]
@gregor-tusar-sowa I wonder if the app had gone to sleep, and you were the unfortunate one to wake it up...
