### ISSUE TITLE
Direct URL to Author Packages does not work.

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco.Marketplace.Issues#84]
On a package detail there is a link to author packages:

![author-link](https://github.com/user-attachments/assets/54c594b5-2086-4a7a-a964-8656cfa88ed4)

If you click the link you correctly see all packages by that author:

![all-via-link](https://github.com/user-attachments/assets/42249ed5-654e-494a-8309-e9f4c6f37b68)

The browser URL will change however if you try to use this URL to directly access the authors packages no results are returned:

![all-via-url](https://github.com/user-attachments/assets/4ae33763-e54c-4b1e-a460-e72b9b6de38e)

**Comment by AndyButland** [comment]
This should be resolved now @marcloveUSN.  Issue stemmed from casing... we've made a change to lower-case incoming requested URLs for SEO efforts, and given we are getting the package owner from the URL, that meant a case sensitive search no longer matched.  Having made this case insensitive you should find it working now as expected.

**Comment by marcloveUSN** [comment]
Amazing, thanks Andy for the quick fix.
