### ISSUE TITLE
Package Hall of Fame

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco.Marketplace.Issues#85]
At the moment there is a link to package award winners on the marketplace.

https://marketplace.umbraco.com/awards/2024

Hall of Fame Winners are not mentioned on this. I am suggesting that either they are included on this current list or get their own dedicated page on the marketplace.

---
_This item has been added to our backlog AB#42809_

**Comment by nathanwoulfe** [comment]
Heya @marcloveUSN 100% agree - we discussed this internally, and I'm sure it landed on the backlog (probably around the same time all my European colleagues disappeared for summer). We will make it happen.

**Comment by marcloveUSN** [comment]
Nice one @nathanwoulfe. Thanks for looking into this.

**Comment by nathanwoulfe** [comment]
Hey @marcloveUSN https://marketplace.umbraco.com/awards/hall-of-fame is now a thing. Thanks for the reminder!

**Comment by marcloveUSN** [comment]
@nathanwoulfe Thanks for the update. Without the direct link though how do people find it? Could it be a category amongst the main sections? Should probably also be a category for all package winners?

![hall-of-fame](https://github.com/user-attachments/assets/6f0d8708-4b89-4ed6-8b8e-9a70d7a834e8)

**Comment by nathanwoulfe** [comment]
@marcloveUSN you're a step ahead of us - next job is to improve the visibility of all award winning packages, and make the listing  pages easily discoverable. For now though, for impressing colleagues and potential clients, you'll need the direct link 😁

**Comment by marcloveUSN** [comment]
@nathanwoulfe Sounds good. Looking forward to seeing it come together 👍

**Comment by nathanwoulfe** [comment]
Heya @marcloveUSN, you may have already seen the updates, but we've added a new homepage section to surface the awardees from each year, and tweaked the badges on package cards to highlight award winners and HoF members.

![image](https://github.com/user-attachments/assets/d7dd3deb-7479-47b7-9659-34ffb2567f01)

**Comment by marcloveUSN** [comment]
Amazing, great addition. Thanks for working on this.
