### ISSUE TITLE
Awards badge not appearing on main listing.

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco.Marketplace.Issues#86]
Packages with awards get a badge on the Hall of Fame Page. See image below.

![hof](https://github.com/user-attachments/assets/721c71f3-deb2-4e1a-9d36-cb79110693a4)

This badge should appear on all pages where the package is listed. This is a category page and the badge is missing.

![category-list](https://github.com/user-attachments/assets/e8a2b53f-8fb2-44a8-b3ff-9da0c98b2082)

**Comment by nathanwoulfe** [comment]
Oops, oversight on our part (obviously). I'll fix this up today.
