### ISSUE TITLE
Selecting a category or using the search shows the 404 page

### ISSUE THREAD

**Issue by rolorogan** [umbraco/Umbraco.Marketplace.Issues#88]
If you click on a category or try searching the results appear (e.g. https://marketplace.umbraco.com/category/commerce) but around a second later the 404 error page appears. https://marketplace.umbraco.com/error/404

<img width="1103" alt="Screenshot 2024-10-01 at 15 20 14" src="https://github.com/user-attachments/assets/da20cd2b-1c08-44a1-8a9a-3d50df555ec7">

**Comment by nathanwoulfe** [comment]
Hey @rolorogan thanks for the heads up, this is fixed and working correctly again.
