### ISSUE TITLE
Styling issues with long package names

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Marketplace.Issues#9]
A couple of styling issues with long package names @nathanwoulfe 

![image](https://user-images.githubusercontent.com/1389894/203746613-8750b5a3-c7b0-4dab-97f9-fb5b25802b4e.png)

**Comment by nathanwoulfe** [comment]
Consider it sorted. Won't be pretty but won't be overflowing.

**Comment by AndyButland** [comment]
This looks to have been resolved such that it no longer overflows.  We have also added a `Title` field to the `umbraco-marketplace.json` file, allowing an alternate title to be provided which will be presented instead of the package Id.
